import {StyleSheet} from "react-native";

export default StyleSheet.create({
    container: {
        marginTop: 60
    },
    row: {
        flexDirection: "row",
        flexWrap: "wrap"
    },
    margin: {
        margin: 5
    }, padding: {
        padding: 5
    }, avatar: {
        width: 120,
        height: 120,
        borderRadius: 50
    }, title: {
        fontSize: 30,
        fontWeight: "bold",
        color: "blue",
        alignSelf: "center"
    },
    m0: {margin: 0},
    m1: {margin: 4},
    m2: {margin: 8},
    m3: {margin: 12},
    m4: {margin: 16},
    m5: {margin: 20},
    m6: {margin: 24},
    m8: {margin: 32},
    m10: {margin: 40},
    m12: {margin: 48},
    m16: {margin: 64},
    m20: {margin: 80},

    mt0: {marginTop: 0},
    mt1: {marginTop: 4},
    mt2: {marginTop: 8},
    mt3: {marginTop: 12},
    mt4: {marginTop: 16},
    mt5: {marginTop: 20},
    mt6: {marginTop: 24},
    mt8: {marginTop: 32},
    mt10: {marginTop: 40},
    mt12: {marginTop: 48},
    mt16: {marginTop: 64},
    mt20: {marginTop: 80},

    mb0: {marginBottom: 0},
    mb1: {marginBottom: 4},
    mb2: {marginBottom: 8},
    mb3: {marginBottom: 12},
    mb4: {marginBottom: 16},
    mb5: {marginBottom: 20},
    mb6: {marginBottom: 24},
    mb8: {marginBottom: 32},
    mb10: {marginBottom: 40},
    mb12: {marginBottom: 48},
    mb16: {marginBottom: 64},
    mb20: {marginBottom: 80},

    ml0: {marginLeft: 0},
    ml1: {marginLeft: 4},
    ml2: {marginLeft: 8},
    ml3: {marginLeft: 12},
    ml4: {marginLeft: 16},
    ml5: {marginLeft: 20},
    ml6: {marginLeft: 24},
    ml8: {marginLeft: 32},
    ml10: {marginLeft: 40},
    ml12: {marginLeft: 48},
    ml16: {marginLeft: 64},
    ml20: {marginLeft: 80},

    mr0: {marginRight: 0},
    mr1: {marginRight: 4},
    mr2: {marginRight: 8},
    mr3: {marginRight: 12},
    mr4: {marginRight: 16},
    mr5: {marginRight: 20},
    mr6: {marginRight: 24},
    mr8: {marginRight: 32},
    mr10: {marginRight: 40},
    mr12: {marginRight: 48},
    mr16: {marginRight: 64},
    mr20: {marginRight: 80},

    mx0: {marginHorizontal: 0},
    mx1: {marginHorizontal: 4},
    mx2: {marginHorizontal: 8},
    mx3: {marginHorizontal: 12},
    mx4: {marginHorizontal: 16},
    mx5: {marginHorizontal: 20},
    mx6: {marginHorizontal: 24},
    mx8: {marginHorizontal: 32},
    mx10: {marginHorizontal: 40},

    my0: {marginVertical: 0},
    my1: {marginVertical: 4},
    my2: {marginVertical: 8},
    my3: {marginVertical: 12},
    my4: {marginVertical: 16},
    my5: {marginVertical: 20},
    my6: {marginVertical: 24},
    my8: {marginVertical: 32},
    my10: {marginVertical: 40},

    p0: {padding: 0},
    p1: {padding: 4},
    p2: {padding: 8},
    p3: {padding: 12},
    p4: {padding: 16},
    p5: {padding: 20},
    p6: {padding: 24},
    p8: {padding: 32},
    p10: {padding: 40},
    p12: {padding: 48},
    p16: {padding: 64},
    p20: {padding: 80},

    pt0: {paddingTop: 0},
    pt1: {paddingTop: 4},
    pt2: {paddingTop: 8},
    pt3: {paddingTop: 12},
    pt4: {paddingTop: 16},
    pt5: {paddingTop: 20},
    pt6: {paddingTop: 24},
    pt8: {paddingTop: 32},
    pt10: {paddingTop: 40},
    pt12: {paddingTop: 48},

    pb0: {paddingBottom: 0},
    pb1: {paddingBottom: 4},
    pb2: {paddingBottom: 8},
    pb3: {paddingBottom: 12},
    pb4: {paddingBottom: 16},
    pb5: {paddingBottom: 20},
    pb6: {paddingBottom: 24},
    pb8: {paddingBottom: 32},
    pb10: {paddingBottom: 40},
    pb12: {paddingBottom: 48},

    pl0: {paddingLeft: 0},
    pl1: {paddingLeft: 4},
    pl2: {paddingLeft: 8},
    pl3: {paddingLeft: 12},
    pl4: {paddingLeft: 16},
    pl5: {paddingLeft: 20},
    pl6: {paddingLeft: 24},
    pl8: {paddingLeft: 32},
    pl10: {paddingLeft: 40},
    pl12: {paddingLeft: 48},

    pr0: {paddingRight: 0},
    pr1: {paddingRight: 4},
    pr2: {paddingRight: 8},
    pr3: {paddingRight: 12},
    pr4: {paddingRight: 16},
    pr5: {paddingRight: 20},
    pr6: {paddingRight: 24},
    pr8: {paddingRight: 32},
    pr10: {paddingRight: 40},
    pr12: {paddingRight: 48},

    px0: {paddingHorizontal: 0},
    px1: {paddingHorizontal: 4},
    px2: {paddingHorizontal: 8},
    px3: {paddingHorizontal: 12},
    px4: {paddingHorizontal: 16},
    px5: {paddingHorizontal: 20},
    px6: {paddingHorizontal: 24},
    px8: {paddingHorizontal: 32},
    px10: {paddingHorizontal: 40},

    py0: {paddingVertical: 0},
    py1: {paddingVertical: 4},
    py2: {paddingVertical: 8},
    py3: {paddingVertical: 12},
    py4: {paddingVertical: 16},
    py5: {paddingVertical: 20},
    py6: {paddingVertical: 24},
    py8: {paddingVertical: 32},
    py10: {paddingVertical: 40},

    gap1: {gap: 4},
    gap2: {gap: 8},
    gap3: {gap: 12},
    gap4: {gap: 16},
    gap5: {gap: 20},
    gap6: {gap: 24},
    gap8: {gap: 32},
});