# Generated by Django 5.2.7 on 2026-01-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
