# Generated by Django 5.2.7 on 2026-01-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
