# Generated by Django 5.2.7 on 2026-01-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_skill_candidateprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_first_language',
            field=models.BooleanField(default=False, verbose_name='Là ngôn ngữ mẹ đẻ'),
        ),
    ]
