# Generated by Django 5.2.7 on 2026-08-19 08:25

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJobChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('chunk_id', models.CharField(max_length=255, unique=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('source', models.CharField(db_index=True, max_length=50)),
                ('source_job_id', models.CharField(db_index=True, max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('section', models.CharField(db_index=True, max_length=50)),
                ('content', models.TextField()),
                ('location_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('experience_level', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('category_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'ordering': ['source', 'source_job_id', 'chunk_index'],
                'indexes': [models.Index(fields=['source', 'source_job_id'], name='career_source_job_idx')],
            },
        ),
    ]
