# Generated by Django 5.2.7 on 2026-08-03 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationMatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('MATCHING', 'Matching'), ('EXPLAINING', 'Explaining'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('partial_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True, default='')),
                ('cv_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('job_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('job_snapshot', models.JSONField(blank=True, default=dict)),
                ('parser_version', models.CharField(default='document-text-v1', max_length=50)),
                ('matcher_version', models.CharField(default='exact-alias-v1', max_length=50)),
                ('scoring_version', models.CharField(default='required-skill-ratio-v1', max_length=50)),
                ('embedding_version', models.CharField(blank=True, default='', max_length=100)),
                ('prompt_version', models.CharField(blank=True, default='', max_length=50)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_analyses', to='applications.application')),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['application', 'status'], name='app_match_status_idx')],
            },
        ),
    ]
