# Generated by Django 5.2.7 on 2026-01-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookmarkJob',
        ),
    ]
