# Generated by Django 5.2.7 on 2026-01-16 15:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('employer_note', models.TextField(blank=True, default='')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cover_letter', models.TextField(blank=True, default='')),
                ('cv', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
