# Generated by Django 5.2.7 on 2026-01-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duration_days', models.IntegerField(default=7)),
                ('description', models.TextField(blank=True)),
                ('pack_type', models.CharField(default='JOB_PUSH', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tiền mặt'), ('VNPAY', 'VNPAY-QR / ATM')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('SUCCESS', 'Thanh toán thành công'), ('FAILED', 'Thanh toán thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
