# Generated by Django 5.2.7 on 2026-01-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('MOMO', 'Ví MoMo'), ('ZALOPAY', 'ZaloPay'), ('STRIPE', 'Stripe (Visa/Master)'), ('PAYPAL', 'PayPal'), ('VNPAY', 'VNPAY-QR / ATM')], max_length=20),
        ),
    ]
