import {StyleSheet} from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9F9F9',
    },
    content: {
        paddingHorizontal: 20,
        paddingBottom: 36,
    },
    loadingContainer: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        marginTop: 12,
        color: '#524B6B',
        fontSize: 14,
    },
    pageTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#130160',
        marginBottom: 4,
    },
    pageSubtitle: {
        fontSize: 14,
        color: '#524B6B',
        marginBottom: 20,
    },
    errorBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFF4E5',
        borderRadius: 12,
        padding: 12,
        marginBottom: 16,
    },
    errorText: {
        flex: 1,
        color: '#AF5510',
        fontSize: 13,
        marginLeft: 8,
    },
    historySection: {
        marginBottom: 20,
    },
    historyTitle: {
        color: '#524B6B',
        fontSize: 13,
        fontWeight: '600',
        marginBottom: 8,
    },
    historyList: {
        gap: 8,
    },
    historyItem: {
        minWidth: 100,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#EAEAEA',
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    historyItemActive: {
        backgroundColor: '#130160',
        borderColor: '#130160',
    },
    historyItemDate: {
        color: '#524B6B',
        fontSize: 11,
        marginBottom: 3,
    },
    historyItemDateActive: {
        color: 'rgba(255, 255, 255, 0.75)',
    },
    historyItemScore: {
        color: '#130160',
        fontSize: 14,
        fontWeight: '700',
        textTransform: 'capitalize',
    },
    historyItemScoreActive: {
        color: '#FFFFFF',
    },
    summaryCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        shadowColor: '#130160',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    scoreCircle: {
        width: 84,
        height: 84,
        borderRadius: 42,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    scoreValue: {
        fontSize: 26,
        fontWeight: '700',
    },
    scoreSuffix: {
        fontSize: 11,
        fontWeight: '600',
        marginTop: -2,
    },
    summaryContent: {
        flex: 1,
    },
    scoreBadge: {
        alignSelf: 'flex-start',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 4,
        marginBottom: 7,
    },
    scoreBadgeText: {
        fontSize: 11,
        fontWeight: '700',
    },
    summaryTitle: {
        color: '#130160',
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 3,
    },
    summaryText: {
        color: '#77728B',
        fontSize: 12,
        lineHeight: 18,
    },
    explanationCard: {
        backgroundColor: '#FFF4E5',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    explanationHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    explanationTitle: {
        color: '#130160',
        fontSize: 15,
        fontWeight: '700',
        marginLeft: 8,
    },
    explanationText: {
        color: '#524B6B',
        fontSize: 13,
        lineHeight: 20,
    },
    breakdownCard: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#F0F0F0',
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
    },
    cardTitle: {
        color: '#130160',
        fontSize: 16,
        fontWeight: '700',
    },
    breakdownRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: 12,
        marginTop: 2,
        borderTopWidth: 1,
        borderTopColor: '#F3F2F8',
    },
    breakdownLabel: {
        color: '#524B6B',
        fontSize: 13,
    },
    breakdownValue: {
        color: '#130160',
        fontSize: 14,
        fontWeight: '700',
    },
    detailSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sectionIcon: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    sectionIconMatched: {backgroundColor: '#E8F7F0'},
    sectionIconPartial: {backgroundColor: '#FFF4E5'},
    sectionIconMissing: {backgroundColor: '#FFF0F0'},
    sectionIconTextMatched: {color: '#168A63'},
    sectionIconTextPartial: {color: '#AF5510'},
    sectionIconTextMissing: {color: '#C34343'},
    sectionTitle: {
        flex: 1,
        color: '#130160',
        fontSize: 15,
        fontWeight: '700',
    },
    sectionCount: {
        minWidth: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#F3F2F8',
        color: '#524B6B',
        fontSize: 12,
        fontWeight: '700',
        textAlign: 'center',
        textAlignVertical: 'center',
        overflow: 'hidden',
    },
    skillList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 14,
    },
    skillChip: {
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 7,
    },
    skillChipMatched: {backgroundColor: '#E8F7F0'},
    skillChipPartial: {backgroundColor: '#FFF4E5'},
    skillChipMissing: {backgroundColor: '#FFF0F0'},
    skillChipText: {
        fontSize: 12,
        fontWeight: '500',
    },
    skillChipTextMatched: {color: '#168A63'},
    skillChipTextPartial: {color: '#AF5510'},
    skillChipTextMissing: {color: '#C34343'},
    emptySectionText: {
        color: '#AAA6B9',
        fontSize: 13,
        fontStyle: 'italic',
        marginTop: 14,
    },
    evidenceCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        marginBottom: 12,
    },
    evidenceHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 6,
    },
    evidenceItem: {
        paddingVertical: 12,
        borderTopWidth: 1,
        borderTopColor: '#F3F2F8',
    },
    evidenceSkills: {
        color: '#7551FF',
        fontSize: 12,
        fontWeight: '700',
        marginBottom: 5,
    },
    evidenceText: {
        color: '#524B6B',
        fontSize: 13,
        lineHeight: 19,
    },
    emptyCard: {
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        paddingHorizontal: 24,
        paddingVertical: 32,
        borderWidth: 1,
        borderColor: '#F0F0F0',
    },
    emptyIcon: {
        width: 68,
        height: 68,
        borderRadius: 34,
        backgroundColor: '#FFF4E5',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    emptyTitle: {
        color: '#130160',
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 8,
    },
    emptyText: {
        color: '#524B6B',
        fontSize: 13,
        lineHeight: 20,
        textAlign: 'center',
        marginBottom: 24,
    },
    runButton: {
        width: '100%',
        minHeight: 52,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#130160',
        borderRadius: 12,
    },
    runButtonText: {
        color: '#FFFFFF',
        fontSize: 13,
        fontWeight: '700',
        marginLeft: 8,
    },
    failedCard: {
        alignItems: 'center',
        backgroundColor: '#FFF0F0',
        borderRadius: 16,
        padding: 24,
    },
    failedTitle: {
        color: '#C34343',
        fontSize: 16,
        fontWeight: '700',
        marginTop: 10,
        marginBottom: 6,
    },
    failedText: {
        color: '#7E4A4A',
        fontSize: 13,
        lineHeight: 20,
        textAlign: 'center',
        marginBottom: 18,
    },
    retryButton: {
        borderWidth: 1,
        borderColor: '#C34343',
        borderRadius: 10,
        paddingHorizontal: 18,
        paddingVertical: 10,
    },
    retryButtonText: {
        color: '#C34343',
        fontSize: 12,
        fontWeight: '700',
    },
    pendingCard: {
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#F0F0F0',
        padding: 28,
    },
    pendingTitle: {
        color: '#130160',
        fontSize: 16,
        fontWeight: '700',
        marginTop: 14,
        marginBottom: 5,
    },
    pendingText: {
        color: '#524B6B',
        fontSize: 13,
    },
    detailLoading: {
        paddingVertical: 28,
        alignItems: 'center',
    },
});
